import { jsPDF } from 'jspdf';
import { AnalysisResult } from '../types';

export const downloadPDF = async (data: AnalysisResult, options: { redact: boolean }) => {
  // Simulate network delay to mimic a backend API call
  await new Promise(resolve => setTimeout(resolve, 800));

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let y = 20;

  // Helper for text wrapping
  const addWrappedText = (text: string, fontSize: number, color: [number, number, number], isBold = false) => {
    doc.setFontSize(fontSize);
    doc.setTextColor(...color);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, contentWidth);
    
    // Check page break
    if (y + (lines.length * fontSize * 0.5) > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
    
    doc.text(lines, margin, y);
    y += (lines.length * fontSize * 0.4) + 4; // Line height + padding
  };

  // Header
  doc.setFontSize(22);
  doc.setTextColor(30, 64, 175); // Blue-800
  doc.setFont('helvetica', 'bold');
  doc.text("HealthLens AI Analysis", margin, y);
  y += 10;

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // Slate-500
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
  y += 5;
  doc.text(`Version: 1.0.0`, margin, y);
  y += 10;

  if (options.redact) {
    doc.setFillColor(254, 226, 226); // Red-100
    doc.setDrawColor(239, 68, 68); // Red-500
    doc.rect(margin, y, 60, 8, 'FD');
    doc.setTextColor(185, 28, 28); // Red-700
    doc.setFontSize(8);
    doc.text("PATIENT DATA REDACTED", margin + 2, y + 5);
    y += 15;
  }

  // Disclaimer Line
  doc.setDrawColor(203, 213, 225);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;
  addWrappedText("PRIVACY NOTICE: This document contains sensitive medical information. Handle with care.", 8, [100, 116, 139], true);
  y += 5;

  // Summary
  addWrappedText("Simple Summary", 16, [30, 58, 138], true);
  addWrappedText(data.simpleSummary.text, 11, [51, 65, 85]);
  y += 5;

  // Findings
  addWrappedText("Key Findings", 16, [30, 58, 138], true);
  data.keyFindings.forEach(finding => {
    let statusColor: [number, number, number] = [34, 197, 94]; // Green
    let statusText = "NORMAL";
    
    if (finding.status === 'urgent') {
      statusColor = [239, 68, 68];
      statusText = "URGENT";
    } else if (finding.status === 'attention') {
      statusColor = [245, 158, 11];
      statusText = "ATTENTION";
    }

    // Check for page break before rendering finding block
    if (y + 20 > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage();
        y = margin;
    }

    // Status Badge
    doc.setFillColor(...statusColor);
    doc.rect(margin, y - 3, 20, 5, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.text(statusText, margin + 2, y + 1);
    
    // Label
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(11);
    doc.text(finding.label, margin + 25, y + 1);
    
    // Value
    if (finding.extractedValue) {
        doc.text(`${finding.extractedValue.value} ${finding.extractedValue.unit}`, pageWidth - margin - 30, y + 1);
    }
    
    y += 7;
    
    // Snippet
    doc.setTextColor(100, 116, 139);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.text(`Source: "${finding.sourceSnippet}"`, margin + 25, y);
    y += 8;
  });
  
  y += 5;

  // Questions
  addWrappedText("Questions for Doctor", 16, [30, 58, 138], true);
  data.questionsForDoctor.forEach((q, i) => {
    addWrappedText(`${i + 1}. ${q}`, 11, [51, 65, 85]);
  });
  y += 5;

  // Practical Implications
  addWrappedText("Practical Implications", 16, [30, 58, 138], true);
  data.practicalImplications.forEach(imp => {
     addWrappedText(`• ${imp}`, 11, [51, 65, 85]);
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} - Generated by HealthLens AI`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
  }

  doc.save(`healthlens-analysis-${Date.now()}.pdf`);
};